### ISSUE TITLE
Does not work with python3.5

### ISSUE THREAD

**Issue by AndrewCopeland** [cyberark/conjur-api-python3#43]
## Summary
Currently I cannot initialize a client when using python3.5.

## Steps to Reproduce
1. Setup python3.5
2. Try to init the conjur client
3. Receive an exception

## Expected Results
successfully init the client :D 

## Actual Results (including error logs, if applicable)
```
    from conjur import Client
  File "/root/.local/lib/python3.5/site-packages/conjur/__init__.py", line 29, in <module>
    from .client import Client
  File "/root/.local/lib/python3.5/site-packages/conjur/client.py", line 12, in <module>
    from .api import Api
  File "/root/.local/lib/python3.5/site-packages/conjur/api.py", line 15, in <module>
    from .http import HttpVerb, invoke_endpoint
  File "/root/.local/lib/python3.5/site-packages/conjur/http.py", line 11, in <module>
    from enum import auto, Enum
ImportError: cannot import name 'auto'
```

## Additional Information
I think we should either decide to fix it or decide if python 3.5 is not supported for this library.

**Comment by sgnn7** [comment]
If this is the only problem, this should be easy to fix - `auto` is a pretty easy workaround. Let me see if I can get you a quick fix for this.

**Comment by sgnn7** [comment]
@AndrewCopeland Try the master branch now - fix for this specific error is merged by there may be other packages that need fixing. I'll close this issue but feel free to reopen if it's still an issue.
